# Core variables for Python SQL Web App deployment
# Following Azure Developer CLI (AZD) requirements and Azure CAF naming conventions

variable "environment_name" {
  description = "The name of the azd environment. Required by AZD."
  type        = string
  default     = "dev"

  validation {
    condition     = can(regex("^[a-z0-9-]{1,64}$", var.environment_name))
    error_message = "Environment name must be lowercase alphanumeric with hyphens, max 64 characters."
  }
}

variable "location" {
  description = "The Azure region where resources will be created. Required by AZD."
  type        = string
  default     = "East US"
}

variable "resource_group_name" {
  description = "The name of the resource group. Auto-generated by AZD if not provided."
  type        = string
  default     = ""
}

variable "project_name" {
  description = "The name of the project"
  type        = string
  default     = "python-sql-webapp"

  validation {
    condition     = can(regex("^[a-z0-9-]{1,24}$", var.project_name))
    error_message = "Project name must be lowercase alphanumeric with hyphens, max 24 characters."
  }
}

# Tagging variables for governance and cost management
variable "owner" {
  description = "The owner of the resources"
  type        = string
  default     = "DevOps Team"
}

variable "cost_center" {
  description = "Cost center for billing allocation"
  type        = string
  default     = "Engineering"
}

variable "business_unit" {
  description = "Business unit responsible for the resources"
  type        = string
  default     = "Technology"
}

variable "criticality" {
  description = "Business criticality of the application"
  type        = string
  default     = "Medium"
  
  validation {
    condition     = contains(["Low", "Medium", "High", "Critical"], var.criticality)
    error_message = "Criticality must be one of: Low, Medium, High, Critical."
  }
}

variable "data_class" {
  description = "Data classification level"
  type        = string
  default     = "Internal"
  
  validation {
    condition     = contains(["Public", "Internal", "Confidential", "Restricted"], var.data_class)
    error_message = "Data class must be one of: Public, Internal, Confidential, Restricted."
  }
}

# Network configuration variables
variable "vnet_address_space" {
  description = "Address space for the virtual network"
  type        = list(string)
  default     = ["10.0.0.0/16"]

  validation {
    condition     = length(var.vnet_address_space) > 0
    error_message = "At least one address space must be provided."
  }
}

variable "allowed_ip_ranges" {
  description = "List of IP ranges allowed to access resources"
  type        = list(string)
  default     = []
}

# Database configuration
variable "sql_admin_login" {
  description = "The administrator login for the SQL server"
  type        = string
  default     = "sqladmin"
  sensitive   = true

  validation {
    condition     = can(regex("^[a-zA-Z][a-zA-Z0-9]{2,127}$", var.sql_admin_login))
    error_message = "SQL admin login must start with a letter and be 3-128 characters long."
  }
}

variable "sql_admin_password" {
  description = "The administrator password for the SQL server"
  type        = string
  sensitive   = true
  default     = null
}

# App Service configuration
variable "app_service_sku" {
  description = "The SKU for the App Service Plan"
  type = object({
    tier = string
    size = string
  })
  default = {
    tier = "Standard"
    size = "S1"
  }

  validation {
    condition = contains(["Free", "Shared", "Basic", "Standard", "Premium", "PremiumV2", "PremiumV3"], var.app_service_sku.tier)
    error_message = "App Service tier must be one of the supported Azure tiers."
  }
}

# SQL Database configuration
variable "sql_database_sku" {
  description = "The SKU for the SQL Database"
  type = object({
    name     = string
    tier     = string
    capacity = number
  })
  default = {
    name     = "Basic"
    tier     = "Basic"
    capacity = 5
  }
}

# Security configuration
variable "enable_private_endpoints" {
  description = "Enable private endpoints for PaaS services"
  type        = bool
  default     = true
}

variable "enable_managed_identity" {
  description = "Enable managed identity for the web app"
  type        = bool
  default     = true
}

variable "key_vault_soft_delete_retention" {
  description = "Soft delete retention period for Key Vault in days"
  type        = number
  default     = 7
  
  validation {
    condition     = var.key_vault_soft_delete_retention >= 7 && var.key_vault_soft_delete_retention <= 90
    error_message = "Key Vault soft delete retention must be between 7 and 90 days."
  }
}